version: '3.9'

services:
  web:
    build: .
    container_name: mini_udp_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_backend:/app
    ports:
      - "8000:8000"
